mappings:
  ShortcodableController: SheaDawson\Shortcodable\Controllers\ShortcodableController
  ShortcodableHtmlEditorField: SheaDawson\Shortcodable\Extensions\ShortcodableHtmlEditorField
  ShortcodableParser: SheaDawson\Shortcodable\Extensions\ShortcodableParser
  Shortcodable: SheaDawson\Shortcodable\Shortcodable
