SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - sheadawson/shortcodable:javascript/editor_plugin.js
    - sheadawson/shortcodable:javascript/shortcodable.js
  extra_requirements_css:
    - sheadawson/shortcodable:css/shortcodable.css
SilverStripe\Control\Director:
  rules:
    admin/shortcodes: SheaDawson\Shortcodable\Controllers\ShortcodableController
SheaDawson\Shortcodable\Shortcodable:
  htmleditor_names:
    - cms
HtmlEditorField:
  extensions:
    - SheaDawson\Shortcodable\Extensions\ShortcodableHtmlEditorField
