---
Name: shortcodable
After:
    - framework/*
    - cms/*
---

LeftAndMain:
  extra_requirements_javascript:
    - silverstripe/shortcodable:javascript/editor_plugin.js
    - silverstripe/shortcodable:javascript/shortcodable.js
  extra_requirements_css:
    - silverstripe/shortcodable:css/shortcodable.css

SilverStripe\Control\Director:
  rules:
    'admin/shortcodable': Silverstripe\Shortcodable\Controller\ShortcodableController

Silverstripe\Shortcodable\Shortcodable:
  htmleditor_names:
    - cms

SilverStripe\Forms\HTMLEditor\HtmlEditorField:
  extensions:
    - Silverstripe\Shortcodable\ShortcodableHtmlEditorField

SilverStripe\View\Parsers\ShortcodeParser:
  extensions:
    - Silverstripe\Shortcodable\ShortcodableShortcodeParserExtension
